# dvc.yaml
stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - params.yaml
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
      - params.yaml
    outs:
      - data/features/train_bow.csv
      - data/features/test_bow.csv

  train_evaluate:
    cmd: python src/train_evaluate.py
    deps:
      - src/train_evaluate.py
      - data/features/train_bow.csv
      - data/features/test_bow.csv
      - params.yaml
    outs:
      - models/model.pkl
      - metrics.json