# params.yaml
data_ingestion:
  test_size: 0.2
  random_state: 42
  url: "https://raw.githubusercontent.com/entbappy/Branching-tutorial/refs/heads/master/tweet_emotions.csv"

preprocessing:
  min_sentence_length: 3

feature_engineering:
  max_features: 50

model:
  n_estimators: 50